name: Upload store MSIX to release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      store-id:
        description: "Microsoft Store product id"
        required: true
      asset-name-pattern:
        description: "Release asset name pattern to replace"
        required: true
        default: "Nyro-Windows-x86_64"

jobs:
  upload-store-msix-to-release:
    runs-on: ubuntu-latest

    steps:
    - name: Upload store MSIX to release
      uses: hiddify/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release@develop
      with:
        store-id: ${{ inputs.store-id }}
        token: ${{ secrets.GITHUB_TOKEN }}
        asset-name-pattern: ${{ inputs.asset-name-pattern }}
